---
abstract: 'Comprehensive and automatic loading, processing, and analysis of CSV files.'
author:
  - 'Aran Deltac <bluefeet@gmail.com>'
build_requires:
  Test::Exception: 0.31
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-CSV-Auto
requires:
  Clone: 0.31
  IO: 1.25
  List::MoreUtils: 0.30
  Module::Pluggable: 3.9
  Moose: 1.24
  Text::CSV: 1.21
  Text::CSV::Separator: 0.20
  autodie: 2.10
  perl: v5.10.0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Text-CSV-Auto
  repository: git://github.com/bluefeet/Text-CSV-Auto.git
version: 0.05
